Style/QuotedSymbols:
  Enabled: true
  EnforcedStyle: single_quotes
  Include:
    - '**/*.js'
    - '**/*.html'
    - '**/*.css'
Style/StringLiterals:
  EnforcedStyle: double_quotes
  Include:
    - '**/*.rb'
    - '**/*.html.rb'
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/PerceivedComplexity:
  Exclude:
    - 'app/controllers/**/*'
Style/ClassAndModuleChildren:
  Enabled: false
