default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "root") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "default_password") %>
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: rails_tutorial_development

test:
  <<: *default
  database: rails_tutorial_test

production:
  <<: *default
  database: rails_tutorial_production
  username: <%= ENV.fetch("RAILS_TUTORIAL_DATABASE_USERNAME", "rails_tutorial") %>
  password: <%= ENV.fetch("RAILS_TUTORIAL_DATABASE_PASSWORD", "production_password") %>
