default: &default
  image_upload:
    resize_to_limit: [240, 240]
    max_size_mb: 5
    allowed_types:
      - "image/png"
      - "image/jpeg"
  model:
    related_to_limit: 3
  rental: 
    rental_limit: 10
    minimum_duration: 4
  jwt:
    expiration_time: 24
development:
  <<: *default

production:
  <<: *default

test:
  <<: *default
