default: &default
  image_upload:
    resize_to_limit: [240, 240]
    max_size_mb: 5
    allowed_types:
      - "image/png"
      - "image/jpeg"
      - "image/jpg"
  model:
    related_to_limit: 3
  rental: 
    rental_limit: 10
    minimum_duration: 4

development:
  <<: *default

production:
  <<: *default
